/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'At0m',
    {
      type: 'category',
      label: 'Research',
      items: [
        'Writeups/Writeups',
        {
          type: 'category',
          label: 'Binary Exploitation',
          items: [{type: 'autogenerated', dirName: 'Writeups/Binary Exploitation'}],
        },
        {
          type: 'category',
          label: 'Digital Forensics',
          items: [{type: 'autogenerated', dirName: 'Writeups/Digital Forensics'}],
        },
        {
          type: 'category',
          label: 'Machine Studies',
          items: [{type: 'autogenerated', dirName: 'Writeups/Hack The Box/Machines'}],
        },
        {
          type: 'category',
          label: 'Reports',
          items: [{type: 'autogenerated', dirName: 'Research'}],
        },
      ],
    },
  ],
};

export default sidebars;
